### ISSUE TITLE
Ability to filter returned Posts for P2P module

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-cpts#1]
```
$relationship_posts = get_posts( array(
    'post_type'   => $relationship,
    'numberposts'  => - 1,
    'post_status' => 'any',
    'order'       => 'ASC',
    'orderby'     => 'title',
) );
```

Currently this is very static. Being able to add more or change Query Arguments via a Filter would be very useful.

For example:
- filtering out unpublished posts
- filtering out child posts
- filtering by taxonomy
- sorting by publish date

**Comment by joelworsham** [comment]
👍
