### ISSUE TITLE
Empty Metabox on Connected To Post Type if the Connected From Post has a Blank Title

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-cpts#3]
Let's say I have the following set up as my P2P Relationships:

```
add_filter( 'p2p_relationships', function( $relationships ) {
    
    $relationships['documentation'] = 'post';
    
    return $relationships;
    
    
} );
```

If I create a Documentation Post with an Empty Title and link it to a Post, on the Post Edit page for that Post it will appear as if it were blank.

Empty Metabox on for Posts:
![image](https://cloud.githubusercontent.com/assets/7770631/17030900/a6746694-4f3f-11e6-86d1-c07439b79399.png)

Maybe it should show "(no title) Post ID: \<post_id\>" in this case?

**Comment by joelworsham** [comment]
Aha, yes that would be good
